sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: cjp
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJy2EuLW6Pe1PnXaeBy
    access-key-secret: cMbFN1tdOpgGZFGEKl7puqqV26cNZX
    bucket-name: sky-part

  redis:
    host: localhost
    port: 6379
    database: 2
